import logging
import re
from datetime import date
from typing import Any, Dict, List

from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

from app.config import settings
from app.models.topic_output import TopicOutput

logger = logging.getLogger(__name__)

_SCOPES = ["https://www.googleapis.com/auth/drive"]
_MIME_TYPE_DOC = "application/vnd.google-apps.document"

_SLACK_LINK_RE = re.compile(r"<(https?://[^|>]+)\|([^>]+)>")
_SLACK_BOLD_RE = re.compile(r"(?<!\*)\*(?!\*)([^*\n]+)\*(?!\*)")
_SLACK_ITALIC_RE = re.compile(r"(?<!_)_(?!_)([^_\n]+)_(?!_)")
_SLACK_HEADING_RE = re.compile(r"^\*([^*]+)\*$")

_PREAMBLE_RE = re.compile(
    r"^\*Antler MENAP.*?Daily Intelligence Digest\*\n_[^\n]*_\n*", re.DOTALL
)
_DEALS_SECTION_RE = re.compile(
    r"\*Key Deals & Funding\*.*?(?=\n\*[^*\n]+\*|\Z)", re.DOTALL
)

_DOC_FOOTER = (
    "This digest is generated automatically from curated MENAP and global "
    "VC sources. Content covers the past 7 days."
)


def _drive_service():
    if not settings.google_service_account_json or not settings.google_drive_folder_id:
        return None
    credentials = service_account.Credentials.from_service_account_info(
        __import__("json").loads(settings.google_service_account_json), scopes=_SCOPES
    )
    return build("drive", "v3", credentials=credentials, cache_discovery=False)


def _slack_mrkdwn_to_plain(slack_mrkdwn: str) -> str:
    """Strip Slack mrkdwn formatting down to plain, email-safe text: resolve
    <url|label> links to 'label (url)', drop emphasis markers, and turn
    bold section-heading lines into plain uppercase headings."""
    lines = []
    for raw_line in slack_mrkdwn.strip().splitlines():
        line = raw_line.strip()
        if not line:
            lines.append("")
            continue

        line = _SLACK_LINK_RE.sub(r"\2 (\1)", line)

        heading_match = _SLACK_HEADING_RE.match(line)
        if heading_match:
            lines.append("")
            lines.append(heading_match.group(1).upper())
            lines.append("")
            continue

        line = _SLACK_BOLD_RE.sub(r"\1", line)
        line = _SLACK_ITALIC_RE.sub(r"\1", line)
        if line.startswith("- "):
            line = "• " + line[2:]
        lines.append(line)

    return "\n".join(lines).strip()


def _format_deals(deals: List[Dict[str, Any]]) -> str:
    if not deals:
        return ""

    lines = ["KEY DEALS & FUNDING", ""]
    for deal in deals:
        company = deal.get("company") or "—"
        country = deal.get("country")
        round_ = deal.get("round") or "—"
        amount = deal.get("amount")
        investors = deal.get("investors")
        source_name = deal.get("source_name")
        source_url = deal.get("source_url")

        parts = [f"{company} ({country})" if country else company, round_]
        if amount:
            parts.append(amount)
        if investors:
            parts.append(investors)
        line = "• " + " — ".join(parts)
        if source_url:
            line += f" ({source_name or source_url})"
        lines.append(line)

    return "\n".join(lines)


def format_digest_for_email(topic_label: str, output: TopicOutput) -> str:
    """Render a TopicOutput as clean, email-safe plain text: no Slack
    mrkdwn, no emoji section markers."""
    digest_date = output.date
    header = f"MENAP VC Digest — {digest_date.strftime('%d %b %Y')}"

    sections = [
        header,
        "Generated by Antler MENAP Intelligence Pipeline",
        f"({topic_label})",
        "",
        "---",
        "",
    ]

    deals_block = _format_deals(output.deals)
    if deals_block:
        sections.append(deals_block)
        sections.append("")

    remaining_mrkdwn = _PREAMBLE_RE.sub("", output.summary_text.strip())
    if deals_block:
        remaining_mrkdwn = _DEALS_SECTION_RE.sub("", remaining_mrkdwn)

    sections.append(_slack_mrkdwn_to_plain(remaining_mrkdwn))
    sections.append("")
    sections.append("---")
    sections.append(_DOC_FOOTER)

    return "\n".join(sections).strip() + "\n"


def _doc_title(digest_date: date) -> str:
    return f"MENAP VC Digest — {digest_date.strftime('%d %b %Y')}"


def _find_existing_doc(service, title: str) -> str | None:
    escaped_title = title.replace("'", "\\'")
    query = (
        f"name = '{escaped_title}' and "
        f"'{settings.google_drive_folder_id}' in parents and "
        "trashed = false"
    )
    response = service.files().list(
        q=query,
        fields="files(id)",
        pageSize=1,
        supportsAllDrives=True,
        includeItemsFromAllDrives=True,
        corpora="drive",
        driveId=settings.google_drive_folder_id,
    ).execute()
    files = response.get("files", [])
    return files[0]["id"] if files else None


async def write_digest_to_drive(topic_label: str, output: TopicOutput) -> None:
    """Write today's digest to a Google Doc in the configured Drive folder,
    overwriting the doc for today if it already exists. No-op if Google
    Drive isn't configured; never raises — a Drive failure must not
    block Slack/email digest delivery."""
    service = _drive_service()
    if not service:
        logger.info("write_digest_to_drive: Google Drive not configured, skipping")
        return

    title = _doc_title(output.date)
    body_text = format_digest_for_email(topic_label, output)

    try:
        existing_id = _find_existing_doc(service, title)

        media_body = _text_upload_media(body_text)
        if existing_id:
            service.files().update(
                fileId=existing_id,
                media_body=media_body,
                supportsAllDrives=True,
            ).execute()
            logger.info("write_digest_to_drive: updated existing doc %r (id=%s)", title, existing_id)
        else:
            file_metadata = {
                "name": title,
                "mimeType": _MIME_TYPE_DOC,
                "parents": [settings.google_drive_folder_id],
            }
            created = service.files().create(
                body=file_metadata,
                media_body=media_body,
                fields="id",
                supportsAllDrives=True,
                includeItemsFromAllDrives=True,
            ).execute()
            logger.info("write_digest_to_drive: created doc %r (id=%s)", title, created.get("id"))
    except HttpError:
        logger.exception("write_digest_to_drive: Drive API call failed for title=%r", title)
    except Exception:
        logger.exception("write_digest_to_drive: unexpected failure for title=%r", title)


def _text_upload_media(text: str):
    import io

    from googleapiclient.http import MediaIoBaseUpload

    return MediaIoBaseUpload(io.BytesIO(text.encode("utf-8")), mimetype="text/plain", resumable=False)
