import os
import datetime
from unittest.mock import MagicMock, patch

import pytest

os.environ.setdefault("MONGODB_URI", "mongodb://localhost:27017")
os.environ.setdefault("VOYAGE_API_KEY", "test-voyage-key")
os.environ.setdefault("POSTMARK_WEBHOOK_TOKEN", "test-token")
os.environ.setdefault("ANTHROPIC_API_KEY", "test-anthropic-key")

from app.models.topic_output import TopicOutput
from app.services import digest_drive_writer


def _patch_drive_configured():
    return patch.multiple(
        digest_drive_writer.settings,
        google_service_account_json='{"type": "service_account"}',
        google_drive_folder_id="folder-123",
    )


SAMPLE_SUMMARY = """*Antler MENAP — Daily Intelligence Digest*
_MENA & Pakistan Startup Ecosystem | Monday, 17 August 2026_

*Key Deals & Funding*
- Keyper raised a $11M Series A <https://example.com/a|Wamda>

*So What?* Early-stage capital keeps flowing into UAE proptech.

*Emerging Trends*
- Fintech's dominance is _structural_, not cyclical <https://example.com/b|MENAbytes>

*So What?* Watch for spillover into adjacent verticals.
"""

SAMPLE_DEALS = [
    {
        "company": "Keyper",
        "country": "UAE",
        "round": "Series A",
        "amount": "$11M",
        "investors": "Speedinvest",
        "source_url": "https://example.com/a",
        "source_name": "Wamda",
    }
]


def _make_output(deals=None) -> TopicOutput:
    return TopicOutput(
        topic_id="menap_general",
        date=datetime.date(2026, 8, 17),
        summary_text=SAMPLE_SUMMARY,
        sources_used=["doc1"],
        generated_at=datetime.datetime.now(datetime.timezone.utc),
        deals=deals or [],
    )


def test_format_digest_for_email_includes_title_and_footer():
    text = digest_drive_writer.format_digest_for_email("MENA & Pakistan Startup Ecosystem", _make_output())
    assert "MENAP VC Digest — 17 Aug 2026" in text
    assert "Generated by Antler MENAP Intelligence Pipeline" in text
    assert "generated automatically from curated MENAP" in text


def test_format_digest_for_email_strips_slack_preamble():
    text = digest_drive_writer.format_digest_for_email("MENA & Pakistan Startup Ecosystem", _make_output())
    assert "Antler MENAP — Daily Intelligence Digest" not in text


def test_format_digest_for_email_resolves_links_and_drops_emphasis():
    text = digest_drive_writer.format_digest_for_email("MENA & Pakistan Startup Ecosystem", _make_output())
    assert "MENAbytes (https://example.com/b)" in text
    assert "_structural_" not in text
    assert "structural" in text


def test_format_digest_for_email_renders_deals_table_once():
    text = digest_drive_writer.format_digest_for_email("MENA & Pakistan Startup Ecosystem", _make_output(SAMPLE_DEALS))
    assert text.count("Keyper") == 1
    assert "KEY DEALS & FUNDING" in text
    assert "UAE" in text
    assert "Series A" in text
    assert "Speedinvest" in text


def test_format_digest_for_email_falls_back_to_prose_when_no_structured_deals():
    text = digest_drive_writer.format_digest_for_email("MENA & Pakistan Startup Ecosystem", _make_output())
    # No structured deals table, but the summary's own prose section survives.
    assert "Keyper raised a $11M Series A" in text


@pytest.mark.asyncio
async def test_write_digest_to_drive_skips_when_not_configured():
    with patch.multiple(digest_drive_writer.settings, google_service_account_json="", google_drive_folder_id=""):
        await digest_drive_writer.write_digest_to_drive("MENA & Pakistan Startup Ecosystem", _make_output())
    # No exception, no service built — nothing further to assert.


@pytest.mark.asyncio
async def test_write_digest_to_drive_creates_new_doc_when_none_exists():
    mock_service = MagicMock()
    mock_service.files.return_value.list.return_value.execute.return_value = {"files": []}
    mock_service.files.return_value.create.return_value.execute.return_value = {"id": "new-doc-id"}

    with _patch_drive_configured(), patch.object(digest_drive_writer, "_drive_service", return_value=mock_service):
        await digest_drive_writer.write_digest_to_drive("MENA & Pakistan Startup Ecosystem", _make_output())

    mock_service.files.return_value.create.assert_called_once()
    create_kwargs = mock_service.files.return_value.create.call_args.kwargs
    assert create_kwargs["body"]["name"] == "MENAP VC Digest — 17 Aug 2026"
    assert create_kwargs["body"]["parents"] == ["folder-123"]


@pytest.mark.asyncio
async def test_write_digest_to_drive_overwrites_existing_doc():
    mock_service = MagicMock()
    mock_service.files.return_value.list.return_value.execute.return_value = {"files": [{"id": "existing-id"}]}
    mock_service.files.return_value.update.return_value.execute.return_value = {"id": "existing-id"}

    with _patch_drive_configured(), patch.object(digest_drive_writer, "_drive_service", return_value=mock_service):
        await digest_drive_writer.write_digest_to_drive("MENA & Pakistan Startup Ecosystem", _make_output())

    mock_service.files.return_value.update.assert_called_once()
    assert mock_service.files.return_value.update.call_args.kwargs["fileId"] == "existing-id"
    mock_service.files.return_value.create.assert_not_called()


@pytest.mark.asyncio
async def test_write_digest_to_drive_never_raises_on_api_failure():
    mock_service = MagicMock()
    mock_service.files.return_value.list.return_value.execute.side_effect = Exception("boom")

    with _patch_drive_configured(), patch.object(digest_drive_writer, "_drive_service", return_value=mock_service):
        await digest_drive_writer.write_digest_to_drive("MENA & Pakistan Startup Ecosystem", _make_output())
    # No exception propagated — that's the assertion.
